server: 
  port: 8081
  jwtissuer: slingshot
  jwtsecretkey: slingshot_jwt_secret_key
  jwtexpireshour: 24
  
database: 
  user: root
  password: root_1234
  host: 127.0.0.1
  port: 3306
  name: slingshot
  param: charset=utf8&parseTime=True&loc=Local